### ISSUE TITLE
“error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory” when running sample 

### ISSUE THREAD

**Issue by Soroorsh** [NVIDIA/TRTorch#157]
I'm trying to run the sample code. I've installed TRTorch according to the official [TRTorch](https://nvidia.github.io/TRTorch/tutorials/installation.html) instruction.
When the sample code is run (with the below command from this link) the given error arise: <br/>
>sudo bazel run //cpp/trtorchexec -- $(realpath /home/TRTorch/tests/modules/alexnet_scripted.jit.pt) "(1,3,228,228)"

>error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

Also, the LD_LIBRARY_PATH is set correctly.

>export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/TensorRT/TensorRT-7.0.0.11/lib

More info:

>TRTorch: latest version (python package and binary) <br/>
>TensorRT: 7.0.0.11 <br/>
>Pytorch: 1.5.1 <br/>
>CUDA: 10.2 <br/>
>Python: 3.6

**Comment by narendasan** [comment]
My guess is that when you run with sudo that you will no longer have the` LD_LIBRARY_PATH` variable set. I believe you can do `sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH bazel ...` to share this enviorment variable with the root user. We also are recommending people to use `trtorchc` which has a better more stable CLI interface btw.

**Comment by Soroorsh** [comment]
@narendasan Thanks for your quick reply. That works for me but another error arises.

>/home/.cache/bazel/_bazel_root/17c3b8408025104c1d1937cf0328cb01/execroot/TRTorch/bazel-out/k8-fastbuild/bin/cpp/trtorchc/trtorchc: error while loading shared libraries: libnvToolsExt-3965bdd0.so.1: cannot open shared object file: No such file or directory

Also, I set the CUDA and TensorRT path according to your instruction.

**Comment by narendasan** [comment]
Do you have the libtorch libraries in your LD_LIBRARY_PATH?

**Comment by Soroorsh** [comment]
Thank you for your answer. I added libtorch and It works. The samples are running correctly and the models are converted.
Now, I want to load the converted model in qt using:

>module = torch::jit::load("Resnet50.jit.pt"); <br/>
module.to(torch::kCUDA); <br/>
std::cout << "loading the model ok\n"; <br/>
auto in = torch::randn({1,3, 224, 224}, {torch::kCUDA}); <br/>
auto trt_mod = CompileGraph(module, std::vector<ExtraInfo::InputRange>{{in.sizes()}}); <br/>
auto out = trt_mod.forward({in}); <br/>

But the given error arise:

>error: undefined reference to `trtorch::ExtraInfo::InputRange::InputRange(c10::ArrayRef<long>)' <br/>
>error: undefined reference to `trtorch::CompileGraph(torch::jit::Module const&, trtorch::ExtraInfo)'

The cmake file is:

>set(Torch_DIR "../pytorch/torch/share/cmake/Torch")
>set(TRTorch_DIR "../TRTorch") <br/>
>include_directories("../TRTorch/cpp/api/include")<br/>
include_directories("../TRTorch/bazel-TRTorch")<br/>
include_directories("../TRTorch/bazel-TRTorch/core")<br/>
include_directories("../TRTorch/bazel-TRTorch/cpp")

Also, there is no folder named "lib" and "include" in root dir (TRTorch folder).

Thanks!

**Comment by narendasan** [comment]
Its better when building with libtrtorch to build the tarball and move outside the bazel workspace. Bazel-bin targets may not always be there based on the last command run.

**Comment by Soroorsh** [comment]
Thank you. I add the *"libtrtorch.so"* in my Cmakelist.txt but I got this errors: 
```
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<std::complex<float> >()'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `getPluginRegistry'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `torch::registerCustomClassMethod(std::shared_ptr<torch::jit::Function>)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `at::getLegacyDeviceTypeInit()'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::getCustomClassTypeMap[abi:cxx11]()'
TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::Dispatcher::reportError(c10::DispatchTable const&, c10::DispatchKey)'
TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `createInferBuilder_INTERNAL'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::Error::Error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `createInferRuntime_INTERNAL'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `torch::jit::freeze_module(torch::jit::Module const&)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<c10::ComplexHalf>()'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::Warning::warn(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `c10::ClassType::addAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<c10::Type> const&, bool)'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `at::detail::computeStorageSize(c10::ArrayRef<long>, c10::ArrayRef<long>)'
TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `at::globalLegacyTypeDispatch()'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<std::complex<double> >()'
/TRTorch/bazel_cpp/libtrtorch/trtorch/lib/libtrtorch.so: undefined reference to `torch::jit::SubgraphRewriter::runOnGraph(std::shared_ptr<torch::jit::Graph>&, std::function<bool (torch::jit::Match const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, torch::jit::Value*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, torch::jit::Value*> > > const&)> const&)'
collect2: error: ld returned 1 exit status 
```

**Comment by narendasan** [comment]
did you also add the libtorch libraries to you CMakefile.txt as well?

**Comment by Soroorsh** [comment]
yep, I've set the libtorch path as the set(Libtorch_DIR "TRTorch/bazel-TRTorch/external/libtorch") in CMakefile.txt , but CMake  can not find it.  :(

**Comment by 1605707467qq** [comment]
> sudo sudo运行` LD_LIBRARY_PATH`运行_ _`sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH bazel ...``trtorchc`

Thanks for your reply. I make the tensorRT in myself environment , so, it can't work in sudo!!
Thank you
